name: Build and Test Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Android SDK
        run: |
          # إعداد دليل SDK
          mkdir -p $HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          
          # تنزيل أدوات سطر الأوامر
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          
          # إنشاء المجلد latest إذا لم يكن موجوداً
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          
          # نقل الأدوات إلى المجلد latest بشكل صحيح
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          
          # حذف المجلد القديم cmdline-tools إذا لزم الأمر
          rm -rf $HOME/android-sdk/cmdline-tools
          
          # إعداد المتغيرات البيئية
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install Android Build Tools and Platform
        run: |
          sdkmanager "build-tools;30.0.3" "platforms;android-30"

      - name: Build with Gradle
        run: ./gradlew build
